  - name: Install conda and dependencies
    run: |
      if [ ! -d ~/miniconda ]
      then
        curl -o ~/miniconda.sh -O  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        chmod +x ~/miniconda.sh
        bash ~/miniconda.sh -b -p $HOME/miniconda
        rm ~/miniconda.sh
        export PATH=$HOME/miniconda/bin:/usr/local/cuda/bin:$PATH
      fi
      conda init bash
    shell: bash
  - name: Install mamba
    run: conda install -y -n base -c conda-forge mamba
    shell: bash
  - name: restore_cache
    uses: actions/cache@v3.3.2
    with:
      key: deps1-{{ .Branch }}-{{ checksum "src/home_robot/environment.yml" }}
      path: UPDATE_ME
  - name: Setup env
    run: "[ -d ~/env_home_robot ] || conda env create -f src/home_robot/environment.yml -p ~/env_home_robot"
    shell: bash
  - name: Add pinocchio IK dependency
    run: |-
      conda activate ~/env_home_robot
      conda install pinocchio>=2.6.17 -c conda-forge  -y
    shell: bash
  - name: save_cache
    uses: actions/cache@v3.3.2
    with:
      path: "~/env_home_robot"
      key: deps1-{{ .Branch }}-{{ checksum "src/home_robot/environment.yml" }}
